---
application:
  name: "adopetme-backend"
  project: "adopetme"
  organization: "QoveryCommunity"
routers:
  - name: "main-adopetme-backend"
    routes:
      - application_name: "adopetme-backend"
        paths:
          - "/*"
