---
application:
  name: "adopetme-backend"
  project: "adopetme"
  organization: "QoveryCommunity"
  storage:
    - name: "test"
      size: "1"
      type: "ssd"
routers:
  - name: "main-adopetme-backend"
    routes:
      - application_name: "adopetme-backend"
        paths:
          - "/*"
