---
application:
  name: "adopetme-backend"
  project: "adopetme"
  organization: "QoveryCommunity"
  storage:
    - name: "test"
      size: "10"
      type: "fast_ssd"
      mount_point: "/mnt/test"
routers:
  - name: "main-adopetme-backend"
    routes:
      - application_name: "adopetme-backend"
        paths:
          - "/*"
